services:
  mysql:
    image: mysql:8.4
    container_name: auditflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auditflow_db
      MYSQL_ROOT_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - auditflow_mysql_data:/var/lib/mysql
volumes:
  auditflow_mysql_data:
