"use client";
import { FormEvent, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
type ChecklistItem = { id: number; category: string; description: string; weightage: number };
const emptyItem = { category: "", description: "", weightage: "" };
export default function AdminPage() {
 const [title,setTitle]=useState(""); const [year,setYear]=useState("2026"); const [item,setItem]=useState(emptyItem); const [items,setItems]=useState<ChecklistItem[]>([]); const [notice,setNotice]=useState(""); const total=useMemo(()=>items.reduce((sum,x)=>sum+x.weightage,0),[items]);
 function addItem(e:FormEvent<HTMLFormElement>){e.preventDefault();const weightage=Number(item.weightage);if(!item.category.trim()||!item.description.trim()||weightage<1)return setNotice("Complete every checklist field with a valid weightage.");if(total+weightage>100)return setNotice("Checklist weightage cannot exceed 100%.");setItems([...items,{id:Date.now(),category:item.category.trim(),description:item.description.trim(),weightage}]);setItem(emptyItem);setNotice("");}
 function createCycle(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!title.trim())return setNotice("Enter an audit cycle title.");if(total!==100)return setNotice(`Checklist weightage is ${total}%. It must equal 100%.`);setNotice(`Success: ${title.trim()} (${year}) was created with ${items.length} checklist items.`);setTitle("");setYear("2026");setItems([]);setItem(emptyItem);}
 return <AppShell><h1 className="text-2xl font-bold">Audit Cycle Setup</h1><p className="mt-1 text-sm text-slate-500">Create a cycle, define weightages, and assign departmental auditors.</p><section className="mt-7 max-w-3xl rounded-xl border bg-white p-6 shadow-sm"><form onSubmit={createCycle}><div className="grid gap-4 sm:grid-cols-2"><Field label="Audit title" value={title} onChange={setTitle} placeholder="Institutional Quality Audit"/><Field label="Audit year" value={year} onChange={setYear} placeholder="2026" type="number"/></div><button disabled={items.length===0} className="mt-5 rounded-md bg-navy px-4 py-2 text-sm font-semibold text-white hover:bg-navy/90 disabled:cursor-not-allowed disabled:opacity-40">Create audit cycle</button></form><div className="mt-7 flex items-center justify-between"><h2 className="font-semibold">Checklist items</h2><span className={`text-sm font-semibold ${total===100?"text-mint":"text-slate-500"}`}>{total}% / 100%</span></div><ChecklistForm item={item} setItem={setItem} onSubmit={addItem}/>{items.length>0&&<ul className="mt-3 divide-y rounded-lg border">{items.map(entry=><li className="flex justify-between gap-4 p-3 text-sm" key={entry.id}><span><b>{entry.category}:</b> {entry.description}</span><span className="font-semibold">{entry.weightage}%</span></li>)}</ul>}{notice&&<p role="status" className={`mt-4 rounded-md p-3 text-sm ${notice.startsWith("Success")?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-800"}`}>{notice}</p>}</section></AppShell>;
}
function ChecklistForm({item,setItem,onSubmit}:{item:typeof emptyItem;setItem:(item:typeof emptyItem)=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={onSubmit} className="mt-3 grid gap-3 rounded-lg bg-slate-50 p-4 sm:grid-cols-[.8fr_1.6fr_.5fr_auto]"><input value={item.category} onChange={e=>setItem({...item,category:e.target.value})} className="rounded-md border bg-white p-2 text-sm focus:ring-2 focus:ring-emerald-400" placeholder="Category"/><input value={item.description} onChange={e=>setItem({...item,description:e.target.value})} className="rounded-md border bg-white p-2 text-sm focus:ring-2 focus:ring-emerald-400" placeholder="Requirement description"/><input value={item.weightage} onChange={e=>setItem({...item,weightage:e.target.value})} className="rounded-md border bg-white p-2 text-sm focus:ring-2 focus:ring-emerald-400" min="1" max="100" type="number" placeholder="Weight %"/><button className="rounded-md border border-navy px-3 py-2 text-sm font-semibold text-navy hover:bg-slate-100 active:scale-95">Add checklist</button></form>}
function Field({label,value,onChange,placeholder,type="text"}:{label:string;value:string;onChange:(value:string)=>void;placeholder:string;type?:string}){return <label className="text-sm font-medium">{label}<input value={value} onChange={e=>onChange(e.target.value)} type={type} className="mt-2 w-full rounded-md border p-2.5 outline-none focus:ring-2 focus:ring-emerald-400" placeholder={placeholder}/></label>}
