"use client";
import { ChangeEvent, useRef, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { CheckCircle2, UploadCloud } from "lucide-react";
const items = ["Laboratory Safety & Equipment", "Course File Completeness", "Research Publications", "Placement & Career Services"];
export default function DepartmentPage() {
  const [uploads, setUploads] = useState<Record<number, { name: string; url: string }>>({});
  const inputRefs = useRef<Array<HTMLInputElement | null>>([]);
  const uploaded = Object.keys(uploads).length; const progress = Math.round((uploaded / items.length) * 100);
  function chooseFile(index: number, event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploads(current => ({ ...current, [index]: { name: file.name, url: `mock://evidence/${Date.now()}-${file.name}` } })); event.target.value = ""; }
  return <AppShell><h1 className="text-2xl font-bold">Department Evidence Hub</h1><p className="mt-1 text-sm text-slate-600">Computer Science & Engineering · Audit Cycle 2026</p><section className="mt-4 border border-slate-400 bg-white p-3"><div className="flex items-center justify-between border-b border-slate-400 pb-2 text-sm"><b>Overall Submission Progress</b><b className="text-green-800">{uploaded} of {items.length} evidence items ({progress}%)</b></div><div className="mt-2 h-4 border border-slate-500 bg-slate-100 p-[2px]"><div className="h-full bg-green-600" style={{ width: `${progress}%` }}/></div></section><section className="mt-4 border border-slate-400 bg-white p-3"><div className="mb-3 border-b border-slate-400 pb-2"><h2 className="font-bold text-black">Evidence Submission Register</h2><p className="text-xs text-slate-600">Upload an approved supporting document for each audit requirement.</p></div><div className="overflow-x-auto"><table className="w-full table-fixed border-collapse border border-slate-400 text-left text-sm"><thead className="bg-slate-200 text-black"><tr><th className="w-12 border border-slate-400 p-2">No.</th><th className="border border-slate-400 p-2">Checklist Requirement</th><th className="w-48 border border-slate-400 p-2">Evidence Status</th><th className="w-40 border border-slate-400 p-2">Action</th></tr></thead><tbody>{items.map((item, index) => <tr className="bg-white" key={item}><td className="border border-slate-400 p-2 text-center">{index + 1}</td><td className="border border-slate-400 p-2 font-medium">{item}</td><td className="border border-slate-400 p-2">{uploads[index] ? <span className="inline-flex items-center gap-1 border border-green-700 bg-green-100 px-2 py-1 text-xs font-bold text-green-900"><CheckCircle2 size={13}/> {uploads[index].name}</span> : <span className="border border-amber-700 bg-amber-100 px-2 py-1 text-xs font-bold text-amber-900">Pending upload</span>}</td><td className="border border-slate-400 p-2"><input ref={element => { inputRefs.current[index] = element; }} onChange={event => chooseFile(index, event)} className="sr-only" type="file" accept=".pdf,image/*,.doc,.docx"/><button type="button" onClick={() => inputRefs.current[index]?.click()} className="inline-flex w-full items-center justify-center gap-1 border-2 border-b-slate-600 border-l-white border-r-slate-600 border-t-white bg-slate-200 px-2 py-1.5 text-xs font-bold text-black hover:bg-slate-300"><UploadCloud size={14}/>{uploads[index] ? "Replace" : "Upload"}</button></td></tr>)}</tbody></table></div></section></AppShell>;
}
