import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { ArrowRight, Building2, CheckCircle2, ClipboardCheck, FileWarning, ShieldCheck } from "lucide-react";
const modules = [
  { href: "/admin", title: "Audit Cycle Setup", text: "Create cycles and maintain weighted compliance checklists.", icon: ClipboardCheck },
  { href: "/department", title: "Evidence Hub", text: "Upload and track evidence against departmental requirements.", icon: Building2 },
  { href: "/auditor", title: "Auditor Review", text: "Score submitted evidence and record corrective actions.", icon: ShieldCheck },
] as const;
export default function Home() { return <AppShell><h1 className="text-2xl font-bold">AuditFlow Control Centre</h1><p className="mt-1 text-sm text-slate-600">Institutional Quality Audit · 2026 Compliance Cycle</p><section className="mt-4 grid gap-3 sm:grid-cols-3"><Stat icon={CheckCircle2} label="Evidence received" value="12 / 16" detail="75% complete" tone="text-green-800"/><Stat icon={FileWarning} label="Open findings" value="03" detail="Requires follow-up" tone="text-amber-900"/><Stat icon={Building2} label="Departments covered" value="04" detail="Current audit cycle" tone="text-blue-950"/></section><section className="mt-4 border border-slate-400 bg-white"><div className="border-b border-slate-400 bg-slate-200 px-3 py-2"><h2 className="font-bold text-black">Audit Workspace</h2></div><div className="grid divide-y divide-slate-400 md:grid-cols-3 md:divide-x md:divide-y-0">{modules.map(({ href, title, text, icon: Icon }) => <Link className="group p-4 hover:bg-blue-50" href={href} key={href}><Icon className="text-slate-600" size={22}/><h3 className="mt-3 font-bold text-blue-950 group-hover:underline">{title}</h3><p className="mt-1 text-sm text-slate-600">{text}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-blue-900">Open module <ArrowRight size={13}/></span></Link>)}</div></section><section className="mt-4 border border-slate-400 bg-white"><div className="border-b border-slate-400 bg-slate-200 px-3 py-2"><h2 className="font-bold text-black">Current Cycle Status</h2></div><div className="grid gap-4 p-4 md:grid-cols-[1fr_auto]"><div><p className="font-bold text-blue-950">Institutional Quality Audit 2026</p><p className="mt-1 text-sm text-slate-600">Four departments are submitting evidence. The auditor review queue is ready for assessment.</p><div className="mt-3 h-4 border border-slate-500 bg-slate-100 p-[2px]"><div className="h-full w-[75%] bg-green-600"/></div></div><Link className="self-center border-2 border-b-slate-600 border-l-white border-r-slate-600 border-t-white bg-slate-200 px-4 py-2 text-center text-sm font-bold text-black hover:bg-slate-300" href="/management">View management dashboard</Link></div></section></AppShell>; }
function Stat({ icon: Icon, label, value, detail, tone }: { icon: typeof CheckCircle2; label: string; value: string; detail: string; tone: string }) { return <article className="border border-slate-400 bg-white p-3"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase text-slate-600">{label}</p><Icon size={17} className="text-slate-600"/></div><p className={`mt-2 text-2xl font-bold ${tone}`}>{value}</p><p className="text-xs text-slate-600">{detail}</p></article>; }
