"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, ClipboardCheck, Building2, ShieldCheck, BarChart3, FileText, ChevronDown, Menu, Sparkles } from "lucide-react";
const links = [["/admin", "Administration", ClipboardCheck], ["/department", "Department Evidence", Building2], ["/auditor", "Auditor Review", ShieldCheck], ["/management", "Management Reports", BarChart3], ["/report", "Audit Report", FileText]] as const;
export function AppShell({ children }: { children: React.ReactNode }) {
 const pathname = usePathname(); const active = links.find(([href]) => pathname === href || (href === "/report" && pathname === "/reports"))?.[1] || "Workspace";
 return <div className="min-h-screen bg-[#f5f7fb] md:flex">
  <aside className="relative w-full overflow-hidden bg-[#102a43] px-4 py-5 text-white md:sticky md:top-0 md:h-screen md:w-72 md:flex-none md:px-5 md:py-7">
   <div className="absolute -right-20 -top-20 h-52 w-52 rounded-full bg-teal-400/15 blur-3xl"/><div className="relative flex items-center justify-between md:block">
    <Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-teal-300 to-cyan-500 text-[#102a43] shadow-lg shadow-cyan-950/20"><ShieldCheck size={22}/></span><span><span className="block text-xl font-extrabold tracking-tight">AuditFlow</span><span className="block text-[10px] uppercase tracking-[.16em] text-slate-400">Quality assurance</span></span></Link><Menu className="md:hidden" size={21}/>
   </div><nav className="relative mt-7 hidden space-y-1 md:block">{links.map(([href, label, Icon]) => { const isActive = pathname === href || (href === "/report" && pathname === "/reports"); return <Link className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition ${isActive ? "bg-white text-[#102a43] shadow-lg shadow-slate-950/10" : "text-slate-300 hover:bg-white/10 hover:text-white"}`} href={href} key={href}><Icon size={18} className={isActive ? "text-teal-600" : "text-slate-400"}/>{label}</Link>; })}</nav>
   <div className="relative mt-8 hidden rounded-2xl border border-white/10 bg-white/5 p-4 md:block"><div className="flex items-center gap-2 text-xs font-semibold text-teal-200"><Sparkles size={14}/> Audit cycle 2026</div><p className="mt-2 text-xs leading-5 text-slate-300">Evidence window closes in <b className="text-white">18 days</b>.</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-3/4 rounded-full bg-teal-400"/></div></div>
  </aside><main className="min-w-0 flex-1 px-4 py-5 sm:px-7 lg:px-10"><header className="mb-7 flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">Institutional quality assurance</p><p className="mt-1 font-bold text-slate-700">{active}</p></div><div className="flex items-center gap-3"><button type="button" aria-label="Notifications" className="grid h-10 w-10 place-items-center rounded-xl border bg-white text-slate-500 shadow-sm transition hover:text-teal-600"><Bell size={18}/></button><button type="button" className="flex items-center gap-2 rounded-xl border bg-white py-1.5 pl-2 pr-3 text-xs font-semibold text-slate-700 shadow-sm"><span className="grid h-7 w-7 place-items-center rounded-lg bg-teal-100 text-teal-700">NK</span><span className="hidden sm:inline">Nisha Kapoor</span><ChevronDown size={14}/></button></div></header>{children}</main></div>;
}
