"use client";
import { DragDropContext, Droppable, Draggable, DropResult } from "@hello-pangea/dnd";
import { BarChart, Bar, RadarChart, Radar, PolarGrid, PolarAngleAxis, ResponsiveContainer, XAxis, YAxis, Tooltip } from "recharts";
import { useEffect, useState } from "react";
type Item = { id: string; title: string; department: string; due: string };
const scoreData = [{ name: "CSE", score: 86 }, { name: "ECE", score: 74 }, { name: "ME", score: 69 }, { name: "CE", score: 80 }];
const radarData = [{ subject: "Academics", CSE: 90 }, { subject: "Research", CSE: 78 }, { subject: "Infra", CSE: 92 }, { subject: "Governance", CSE: 82 }, { subject: "Support", CSE: 88 }];
const initial: Record<string, Item[]> = { OPEN: [{ id: "a1", title: "Calibrate CNC laboratory equipment", department: "ME", due: "Sep 12" }, { id: "a2", title: "Publish course attainment report", department: "ECE", due: "Sep 18" }], IN_PROGRESS: [{ id: "a3", title: "Update faculty training records", department: "CSE", due: "Sep 08" }], RESOLVED: [{ id: "a4", title: "Install safety signage", department: "CE", due: "Aug 28" }] };
export function ManagementDashboard() { const [columns, setColumns] = useState(initial); useEffect(() => { const saved: Item[] = JSON.parse(window.localStorage.getItem("auditflow-action-items") || "[]"); if (saved.length) setColumns(current => ({ ...current, OPEN: [...current.OPEN, ...saved.filter(item => !current.OPEN.some(existing => existing.id === item.id))] })); }, []); function onDragEnd(r: DropResult) { if (!r.destination) return; const source = [...columns[r.source.droppableId]], [moved] = source.splice(r.source.index, 1); const destination = [...columns[r.destination.droppableId]]; destination.splice(r.destination.index, 0, moved); setColumns({ ...columns, [r.source.droppableId]: source, [r.destination.droppableId]: destination }); }
return <><div className="grid gap-5 lg:grid-cols-2"><ChartCard title="Department compliance score"><ResponsiveContainer width="100%" height={250}><BarChart data={scoreData}><defs><linearGradient id="scoreGradient" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#14b8a6"/><stop offset="100%" stopColor="#2563eb"/></linearGradient></defs><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip contentStyle={{ background: "rgba(15,23,42,.88)", border: "1px solid rgba(255,255,255,.2)", borderRadius: 16 }}/><Bar dataKey="score" fill="url(#scoreGradient)" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="CSE quality profile"><ResponsiveContainer width="100%" height={250}><RadarChart data={radarData}><PolarGrid/><PolarAngleAxis dataKey="subject"/><Radar dataKey="CSE" stroke="#60a5fa" strokeWidth={3} fill="#38bdf8" fillOpacity={.28}/><Tooltip contentStyle={{ background: "rgba(15,23,42,.88)", border: "1px solid rgba(255,255,255,.2)", borderRadius: 16 }}/></RadarChart></ResponsiveContainer></ChartCard></div><div className="mt-8"><div className="mb-4"><h2 className="text-xl font-bold">Corrective action tracker</h2><p className="text-sm text-slate-500">Move findings through resolution.</p></div><DragDropContext onDragEnd={onDragEnd}><div className="grid gap-5 lg:grid-cols-3">{Object.entries(columns).map(([key, items]) => <Droppable droppableId={key} key={key}>{provided => <div className="min-h-80 rounded-3xl border border-white/15 bg-white/5 p-3 backdrop-blur-xl" ref={provided.innerRef} {...provided.droppableProps}><div className="mb-3 flex items-center justify-between px-1"><h3 className="text-sm font-bold">{key.replace("_", " ")}</h3><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${key === "OPEN" ? "border-amber-300/30 bg-amber-400/15 text-amber-100" : key === "IN_PROGRESS" ? "border-blue-300/30 bg-blue-400/15 text-blue-100" : "border-emerald-300/30 bg-emerald-400/15 text-emerald-100"}`}>{items.length}</span></div>{items.map((item,index) => <Draggable draggableId={item.id} index={index} key={item.id}>{p => <article className="mb-3 rounded-2xl border border-white/20 bg-white/10 p-4 shadow-xl backdrop-blur-md" ref={p.innerRef} {...p.draggableProps} {...p.dragHandleProps}><p className="font-medium text-sm">{item.title}</p><div className="mt-3 flex justify-between text-xs text-slate-500"><span>{item.department}</span><span>Due {item.due}</span></div></article>}</Draggable>)}{provided.placeholder}</div>}</Droppable>)}</div></DragDropContext></div></> }
function ChartCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">{title}</h2><div className="mt-4">{children}</div></section>; }
